### ISSUE TITLE
PlanToNamedConfiguration('relaxed_home') fails

### ISSUE THREAD

**Issue by garthz** [personalrobotics/herbpy#10]
The current herbpy build apparently cannot run the entry-level tutorial for PlanToNamedConfiguration().  

The following fails from the ipython prompt:
robot.PlanToNamedConfiguration('relaxed_home')

invocation:
rosrun herbpy console.py --sim

Workspace packages, all up to date:
comps
herb_description
herbpy
interactive_markers
or_cdchomp
or_interactivemarker
or_ompl
or_urdf
owd
prpy

Tail of extensive error output:

/homes/garthz/ln/local/ros-hydro/src/prpy/src/prpy/planning/retimer.pyc in RetimeTrajectory(self, robot, path, **kw_args)
     69 
     70         # Compute the timing. This happens in-place.

---> 71         status = RetimeTrajectory(output_traj, False, 1., 1., self.algorithm)
     72 
     73         if status not in [ PlannerStatus.HasSolution,

openrave_exception: openrave (Assert): [/usr/include/boost/smart_ptr/shared_ptr.hpp:418] -> T* boost::shared_ptr<T>::operator->() const [with T = OpenRAVE::PlannerBase], expr: px != 0

**Comment by jeking04** [comment]
I think you need the package or_parabolicsmoother.this is a recently added dependency and we forgot to update the tutorial.

**Comment by garthz** [comment]
Yes, adding or_parabolicsmoother fixes the problem, thanks.

**Comment by siddhss5** [comment]
@garthz, would you please update the tutorial if you haven't already? Sorry for the inconvenience.

**Comment by garthz** [comment]
Good idea.
I added a link from the herbpy tutorial to the new catkin/hydro guide.
I added the required package to the recommended list.
