### ISSUE TITLE
Add lift action

### ISSUE THREAD

**Issue by jeking04** [personalrobotics/herbpy#32]
Add an action to the action library that enables the robot to lift a grabbed object by temporarily disabling collisions with the object.

This will (hopefully) enable the following list of commands to be smoothly executed from a simple herbpy console:

>robot.DetectObjects()
> cup = ... 
> robot.right_arm.Grasp(cup)
> robot.right_arm.Lift(cup)
> robot.right_arm.PlanToNamedConfiguration('home')

**Comment by rachelholladay** [comment]
@jeking is this sufficiently solved with the merger of feature/lift_action ?

**Comment by mkoval** [comment]
It looks like @rachelholladay implemented a `Lift` action in #37. I am closing this.
