### ISSUE TITLE
PlanToBasePose throws zip-related error

### ISSUE THREAD

**Issue by Shushman** [personalrobotics/herbpy#35]
The PlanToBasePose function in the graspfuzeBottle.py example gives the following error:

```
Traceback (most recent call last):
  File "graspFuzeBottle.py", line 65, in <module>
    robot.base.PlanToBasePose(base_pose)
  File "/home/shushman/catkin_ws/src/prpy/src/prpy/base/mobilebase.py", line 66, in wrapper_method
    return self._BasePlanWrapper(delegate_method, args, kw_args) 
  File "/home/shushman/catkin_ws/src/prpy/src/prpy/base/mobilebase.py", line 164, in _BasePlanWrapper
    return self.robot.ExecutePath(traj, **kw_args)
  File "/home/shushman/catkin_ws/src/prpy/src/prpy/base/robot.py", line 404, in ExecutePath
    return do_execute()
  File "/home/shushman/catkin_ws/src/prpy/src/prpy/base/robot.py", line 391, in do_execute
    exec_traj = self.ExecuteTrajectory(traj, defer=False, **kwargs)
  File "/home/shushman/catkin_ws/src/prpy/src/prpy/base/robot.py", line 446, in ExecuteTrajectory
    if not util.IsAtTrajectoryStart(self, traj):
  File "/home/shushman/catkin_ws/src/prpy/src/prpy/util.py", line 725, in IsAtTrajectoryStart
    dof_infos = zip(dof_indices, traj_values, robot_values, dof_resolutions)
TypeError: zip argument #2 must support iteration
[INFO] [rospy.core:core.py:387]:signal_shutdown: signal_shutdown [atexit]
```

Something to do with the traj_values parameter?

**Comment by cdellin** [comment]
I can confirm that this happens to me regularly on the `table_clearing` demo as well, in particular on the `MoveToPlace Forward` step.  I'm happy to post a traceback, but it looks similar to @Shushman's.

**Comment by jeking04** [comment]
Yup, this is related to prpy issue 153. 

The IsAtTrajectoryStart function does not support affine trajectories. We need to either: 

a. Not call it when we have an affine trajectory
b. Modify the function to behave properly for affine trajectories.  We will also need to modify the sbpl plugin to return a trajectory with the current pose as the first waypoint.

Opinions on which options is better?

**Comment by mkoval** [comment]
I'd prefer (b). I'm not sure, however, how easy this will be to implement.

**Comment by mkoval** [comment]
I see that https://github.com/personalrobotics/prpy/issues/153 is still open. @jeking04 do you know if we've implemented any of these workarounds?

**Comment by jeking04** [comment]
I started an implementation of (b) but didn't get to fully testing it. I'll
see if I can get to it sometime this week.

On Sun, Sep 13, 2015 at 3:23 PM, Michael Koval <notifications@github.com>
wrote:

> I see that personalrobotics/prpy#153
> <https://github.com/personalrobotics/prpy/issues/153> is still open.
> @jeking04 <https://github.com/jeking04> do you know if we've implemented
> any of these workarounds?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/personalrobotics/herbpy/issues/35#issuecomment-139910548>
> .
>



-- 
Jen King

**Comment by mkoval** [comment]
@jeking04 Is this fixed in `master` now?

**Comment by mkoval** [comment]
Fixed in https://github.com/personalrobotics/prpy/pull/188.
