### ISSUE TITLE
Hand Flipped Upside-down for block TSR

### ISSUE THREAD

**Issue by ClintLiddick** [personalrobotics/herbpy#64]
Now that the hand and FT sensor are mounted correctly (plan to home config works correctly), it seems the TSR is flipped, so the extended finger points down and hits the table.

**Comment by mkoval** [comment]
@ClintLiddick Is this still an issue?

**Comment by jeking04** [comment]
I believe we decided the issue was that the hand itself was physically
flipped.

On Monday, February 8, 2016, Michael Koval <notifications@github.com> wrote:

> @ClintLiddick <https://github.com/ClintLiddick> Is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/personalrobotics/herbpy/issues/64#issuecomment-181603990>
> .
>


-- 
Jen King
