### ISSUE TITLE
Possible error in head.MoveTo

### ISSUE THREAD

**Issue by Shushman** [personalrobotics/herbpy#66]
I get this error on typing `robot.head.MoveTo([x,y])` :

`[OWDController.cpp:324 ExecuteORTrajectory] Adding the trajectory to OWD failed with error: Must hold position before calling AddTrajectory`

**Comment by jeking04** [comment]
You just need to call this first:

```
robot.head.SetStiffness(1)
```

Basically the head needs to be stiff before trajectories can be executed.

**Comment by Shushman** [comment]
My bad. It's been a while.
