### ISSUE TITLE
Support for ROSbuild in HERBPpy and other packages

### ISSUE THREAD

**Issue by DavidB-CMU** [personalrobotics/herbpy#70]
Recently the rosbuild manifest file was removed from the herbpy package, however there remains code that applies for rosbuild.

Are we going to gut the packages of all this code?

In my opinion we should create a branch called "rosbuild" or "groovy" which contains the manifest file, and stop maintaining that branch. That way there's a clean, historical copy of all the work that was done. Then in the master branch we can clean out the old code.

**Comment by mkoval** [comment]
Yes, we should be removing all of this code. There are a few reasons:

1. The presence of a `manifest.xml` causes `rosdep` to fail to install Catkin package dependencies.
1. Calling `roslib.load_manifest` can do bad things to your `PYTHONPATH`.
1. Using `roslib.find_package` to find resources does not correctly handle workspace overlays.
1. There is no way to detect if a package is being used in a `catkin` or `rosbuild` context.

It would be nice to maintain a `rosbuild` branch that contains the latest version of the code that worked in `rosbuild`. This is quite a bit harder than it sounds:

1. Most packages stopped working long before we removed the `manifest.xml` file.
1. We did not have a release process or automated tests back in the `rosbuild` days.
1. `hydro` and `groovy` require Ubuntu 12.04, which has quite different library versions than 12.04.
1. Several packages (e.g. `prpy` and `herbpy`) are tightly coupled and must have consistent versions.

If you can figure out which version worked in `rosbuild`, then please do create a branch for it. However, I'm not sure that it's worth the effort.

**Comment by DavidB-CMU** [comment]
Ok yes that all makes sense.

My idea was to tag or branch what we had when manifest.xml was removed, so there was at least some kind of historical record.
But I'm not fussed, it is not impossible to manually check back through commits in the Master branch to find the version when it was removed.

**Comment by mkoval** [comment]
I think we came to an agreement here, so I am closing this issue.
