### ISSUE TITLE
Add Unit Tests for PlanToBasePose() and example code

### ISSUE THREAD

**Issue by DavidB-CMU** [personalrobotics/herbpy#73]
Should SBPL be a required or optional dependency for HERBpy?

The example code uses PlanToBasePose() - how should I make a Unit Test for this if?  If SBPL is a required dependency then it is easier.

**Comment by mkoval** [comment]
I agree with this entirely. However, I think these tests should be on `SBPLPlanner` and live in `prpy`. We should add `or_sbpl` as a `<test_depend>` like we did for the other planners that we test in `prpy`.

@DavidB-CMU Can you move this issue there?

**Comment by DavidB-CMU** [comment]
Issue moved to `prpy` https://github.com/personalrobotics/prpy/issues/268
